### ISSUE TITLE
Cannot read property 'data' of undefined - How to configure prismic?

### ISSUE THREAD

**Issue by conting3ncy** [lhbzr/bruno-arizio#3]
Hello,

When I setup the project locally in vscode I get the below error. I believe it has something to do with my prismic configuration. Could  @lhbzr please provide more details on how to configure prismic in terms of the fields I must create? 

This is how I have setup my custom types in prismic:
![image](https://user-images.githubusercontent.com/37202776/78523926-6eba1280-7826-11ea-99b5-e6bc71ec2c08.png)

When creating my types in prismic, for each type, in the JSON editor tab (when editing) I have pasted in the corresponding .json code found in the /prismic/*.json files. 

When I try the project with the credentials in the "prismic-configuration.js" it works fine:
**.env (works)**
```
PRISMIC_ACCESS_TOKEN=MC5YTGZpTkJRQUFGWmk1eEp1.77-9UzEf77-977-977-977-977-9We-_ve-_ve-_ve-_ve-_vSo4aO-_ve-_ve-_vQgmSO-_vXLvv71o77-977-9XO-_vQ
PRISMIC_CLIENT_ID=XLfiNBQAAFZi5xJt
PRISMIC_CLIENT_SECRET=5be7d81c9c1b8ecd0da6d71ba1edf9f5
PRISMIC_ENDPOINT=https://bruno-arizio.prismic.io/api/v2
```

**.env _(fails and I get the error shown below)_**
```
GOOGLE_ANALYTICS=(my_google_analytics)

PRISMIC_ACCESS_TOKEN=(my_access_token)
PRISMIC_CLIENT_ID=(my_client_id)
PRISMIC_CLIENT_SECRET=(my_client_secret)
PRISMIC_ENDPOINT=(my_end_point)
```

**Resultant Error**
```
TypeError: C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\views\pages\case.pug:13
    11|     +link-arrow-bottom('case__header__button__arrow')
    12| 
  > 13|   section.case(class=`case--${project.data.type.toLowerCase()}` data-index=projectIndex)
    14|     header.case__header
    15|       h1.case__header__title=project.data.name
    16| 

Cannot read property 'data' of undefined
    at eval (eval at wrap (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:157:97)
    at template (eval at wrap (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:555:99)
    at Object.exports.renderFile (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\pug\lib\index.js:427:38)
    at Object.exports.renderFile (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\pug\lib\index.js:417:21)
    at View.exports.__express [as engine] (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\pug\lib\index.js:464:11)
    at View.render (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\node_modules\express\lib\response.js:1008:7)
    at C:\root\bruno-arizio-2f3dd7dd7475862d09e385b2b627c238d8953bfb\app.js:130:14
```

**Comment by osied** [comment]
Did you figure this out? @conting3ncy

**Comment by lhbzr** [comment]
Sorry guys, I'm not being able to keep track of the things on this repo lately. @conting3ncy I think this project have a bug when the filtering of the projects. The `uid` from Prismic needs to match the title of the project, so let's say you have "My Project Name", your `uid` needs to be `my-project-name`, otherwise it's going to fail. It's a bug that I've fixed on my latest projects but didn't had the chance to fix here.

**Comment by osied** [comment]
Change the UID from where? is it from the JSON file on the custom types? can you please direct me or maybe update the file.
